### ISSUE TITLE
package information not updated

### ISSUE THREAD

**Issue by martin-mann** [bioconda/bioconda.github.io#2]
I have pushed a new version of our tool `intarna` (v2.0.0) to bioconda two days ago [bioconda-recipes pull 3720](https://github.com/bioconda/bioconda-recipes/pull/3720).

Unfortunately, the generated page is not (automatically) updating the version information at `bioconda.github.io`:

[https://bioconda.github.io/recipes/intarna/README.html](https://bioconda.github.io/recipes/intarna/README.html)

(should be done every 24h right?)

Guess this is a bug and no feature.. ;)

Thanks for looking into this!

**Comment by johanneskoester** [comment]
There is currently a problem with this, see here: https://travis-ci.org/bioconda/bioconda-utils/jobs/200910798#L909. Most likely one ill-formatted recipe. I am investigating this and hope to fix it ASAP.

**Comment by johanneskoester** [comment]
Should be fixed with PR #3779.

**Comment by martin-mann** [comment]
thanks.. crossing fingers! ;)

**Comment by martin-mann** [comment]
I am sorry, but the problem persists... the `intarna` page still shows v1.2.5 instead of v2.0.0...

any further ideas?

**Comment by johanneskoester** [comment]
I had to fix some additional problems. It should be there now.

**Comment by martin-mann** [comment]
@johanneskoester you are my morning's star ! :) thanks a lot!

**Comment by johanneskoester** [comment]
You're welcome :-).
